/* realpolitiks - data layer: axes, question banks, ideologies, parties, countries */

/* ============ 14 value axes ============ */
const AXES = [
  { id:'econ',  pos:'Equality',        neg:'Markets',       blurb:'Wealth shared by society vs. left to the free market.' },
  { id:'civil', pos:'Liberty',         neg:'Authority',     blurb:'Personal freedom vs. state control and order.' },
  { id:'dmcy',  pos:'Democracy',       neg:'Autocracy',     blurb:'Power held by the people vs. by a strong elite or leader.' },
  { id:'scty',  pos:'Progress',        neg:'Tradition',     blurb:'Embracing social change vs. preserving tradition.' },
  { id:'dipl',  pos:'Globalism',       neg:'Nationalism',   blurb:'World cooperation vs. nation-first sovereignty.' },
  { id:'state', pos:'Localism',        neg:'Centralism',    blurb:'Local and regional power vs. a strong central state.' },
  { id:'ecol',  pos:'Ecology',         neg:'Growth',        blurb:'Protecting the planet vs. prioritising the economy.' },
  { id:'reln',  pos:'Secular',         neg:'Religious',     blurb:'Separating faith from state vs. faith in public life.' },
  { id:'tact',  pos:'Reform',          neg:'Revolution',    blurb:'Gradual change vs. sweeping upheaval of the system.' },
  { id:'mil',   pos:'Pacifism',        neg:'Militarism',    blurb:'Peace and diplomacy vs. military strength and force.' },
  { id:'prop',  pos:'Collective',      neg:'Private',       blurb:'Common ownership vs. private property rights.' },
  { id:'welf',  pos:'Welfare',         neg:'Self-Reliance', blurb:'A strong safety net vs. individual responsibility.' },
  { id:'imm',   pos:'Openness',        neg:'Nativism',      blurb:'Open, multicultural society vs. cultural protection.' },
  { id:'just',  pos:'Rehabilitation',  neg:'Punishment',    blurb:'Reforming offenders vs. tough punishment and order.' }
];

/* ============ General question bank (154) ============ */
/* m: +1 => Agree pushes toward pos pole; -1 => Agree pushes toward neg pole */
const GENERAL = [
  // econ
  {t:'The government should redistribute wealth from the rich to the poor.',ax:'econ',m:1},
  {t:'A large gap between rich and poor is acceptable as long as the economy grows.',ax:'econ',m:-1},
  {t:'Essential services like water and energy should be publicly owned.',ax:'econ',m:1},
  {t:'The free market, not the state, should set wages.',ax:'econ',m:-1},
  {t:'Higher taxes on the wealthy are needed to fund public services.',ax:'econ',m:1},
  {t:'Private business generally serves society better than government programs.',ax:'econ',m:-1},
  {t:'Workers should own and control the companies they work for.',ax:'econ',m:1},
  {t:'Economic inequality is a natural and beneficial feature of society.',ax:'econ',m:-1},
  {t:'A universal basic income should be provided to all citizens.',ax:'econ',m:1},
  {t:'Cutting taxes on business helps everyone through economic growth.',ax:'econ',m:-1},
  {t:'The minimum wage should be significantly increased.',ax:'econ',m:1},
  // civil
  {t:'People should be free to do as they wish provided they harm no one.',ax:'civil',m:1},
  {t:'The government should be able to monitor communications to keep people safe.',ax:'civil',m:-1},
  {t:'Recreational drug use should be decriminalised.',ax:'civil',m:1},
  {t:'National security matters more than personal privacy.',ax:'civil',m:-1},
  {t:'People should be free to criticise the government without restriction.',ax:'civil',m:1},
  {t:'The state has the right to censor dangerous or offensive ideas.',ax:'civil',m:-1},
  {t:'Citizens should have a broad right to own firearms.',ax:'civil',m:1},
  {t:'A strong state is needed to keep order, even at the cost of some freedoms.',ax:'civil',m:-1},
  {t:'Adults should be free to make risky personal choices.',ax:'civil',m:1},
  {t:'Widespread surveillance and mandatory ID checks make society better.',ax:'civil',m:-1},
  {t:'People should have the right to medically assisted dying.',ax:'civil',m:1},
  // dmcy
  {t:'Democracy, despite its flaws, is the best system of government.',ax:'dmcy',m:1},
  {t:'A strong leader who does not have to bother with elections would be good for the country.',ax:'dmcy',m:-1},
  {t:'Ordinary citizens, not elites, should hold ultimate political power.',ax:'dmcy',m:1},
  {t:'Some decisions are too important to be left to ordinary voters.',ax:'dmcy',m:-1},
  {t:'Major national issues should be decided directly by referendum.',ax:'dmcy',m:1},
  {t:'A one-party state can be acceptable if it delivers good results.',ax:'dmcy',m:-1},
  {t:'Leaders should face strict limits on how long they can hold power.',ax:'dmcy',m:1},
  {t:'Political power is better held by a capable elite than by the masses.',ax:'dmcy',m:-1},
  {t:'A free and independent press is essential to hold power to account.',ax:'dmcy',m:1},
  {t:'In a crisis, it is acceptable for a leader to rule by decree.',ax:'dmcy',m:-1},
  {t:'Decisions should be made by elected representatives, not unelected officials.',ax:'dmcy',m:1},
  // scty
  {t:'Society should embrace new social norms and lifestyles.',ax:'scty',m:1},
  {t:'Traditional values are the foundation of a healthy society.',ax:'scty',m:-1},
  {t:'Same-sex marriage should be fully legal and recognised.',ax:'scty',m:1},
  {t:'Society changes too fast and should return to older ways.',ax:'scty',m:-1},
  {t:'Rigid gender roles are outdated and should be abandoned.',ax:'scty',m:1},
  {t:'Long-standing customs deserve respect even when they seem outdated.',ax:'scty',m:-1},
  {t:'Abortion should be legal and accessible.',ax:'scty',m:1},
  {t:'Schools should promote traditional patriotic and moral values.',ax:'scty',m:-1},
  {t:'A diversity of lifestyles makes a nation stronger.',ax:'scty',m:1},
  {t:'Marriage should be defined only as between a man and a woman.',ax:'scty',m:-1},
  {t:'Transgender people should be free to live as their identified gender.',ax:'scty',m:1},
  // dipl
  {t:'Countries should cooperate closely through bodies like the United Nations.',ax:'dipl',m:1},
  {t:'My nation\u2019s interests should always come before global concerns.',ax:'dipl',m:-1},
  {t:'Free movement of people across borders benefits the world.',ax:'dipl',m:1},
  {t:'Global trade deals undermine national sovereignty.',ax:'dipl',m:-1},
  {t:'We should prioritise global human rights over national interest.',ax:'dipl',m:1},
  {t:'Patriotism and national pride are among the highest virtues.',ax:'dipl',m:-1},
  {t:'National borders matter far less than our shared humanity.',ax:'dipl',m:1},
  {t:'International institutions have too much power over individual nations.',ax:'dipl',m:-1},
  {t:'Wealthy countries have a duty to help poorer ones through foreign aid.',ax:'dipl',m:1},
  {t:'Our country should reduce its involvement in foreign alliances.',ax:'dipl',m:-1},
  {t:'A shared global identity matters more than national identity.',ax:'dipl',m:1},
  // state
  {t:'Power should be devolved to local and regional governments.',ax:'state',m:1},
  {t:'A single strong central government governs most effectively.',ax:'state',m:-1},
  {t:'Local communities understand their needs better than the capital.',ax:'state',m:1},
  {t:'National standards should override local decisions.',ax:'state',m:-1},
  {t:'Regions should have the right to self-government or independence.',ax:'state',m:1},
  {t:'A federal system is better than a centralised one.',ax:'state',m:1},
  {t:'Decisions should be made as close to ordinary people as possible.',ax:'state',m:1},
  {t:'The central government should set uniform rules for the whole country.',ax:'state',m:-1},
  {t:'Cities and towns should control their own taxes and spending.',ax:'state',m:1},
  {t:'Too much local control creates chaos and should be limited.',ax:'state',m:-1},
  {t:'Small, self-governing communities are the ideal way to organise society.',ax:'state',m:1},
  // ecol
  {t:'Protecting the environment should take priority over economic growth.',ax:'ecol',m:1},
  {t:'Environmental regulations are an unnecessary burden on business.',ax:'ecol',m:-1},
  {t:'We should rapidly switch to renewable energy even at high cost.',ax:'ecol',m:1},
  {t:'Concerns about climate change are exaggerated.',ax:'ecol',m:-1},
  {t:'Industrial growth and consumption must be limited to save the planet.',ax:'ecol',m:1},
  {t:'A carbon tax should be introduced to cut emissions.',ax:'ecol',m:1},
  {t:'Economic growth matters more than environmental limits.',ax:'ecol',m:-1},
  {t:'Protecting endangered habitats is worth real economic sacrifice.',ax:'ecol',m:1},
  {t:'People should change their lifestyles to help fight climate change.',ax:'ecol',m:1},
  {t:'Strict environmental rules cost jobs and should be relaxed.',ax:'ecol',m:-1},
  {t:'The environment for future generations matters more than present-day profit.',ax:'ecol',m:1},
  // reln
  {t:'Religion should have no influence on government policy.',ax:'reln',m:1},
  {t:'Laws should be grounded in religious or moral tradition.',ax:'reln',m:-1},
  {t:'Public life should be entirely secular.',ax:'reln',m:1},
  {t:'Faith and religious institutions strengthen society.',ax:'reln',m:-1},
  {t:'Religious teaching should help guide education.',ax:'reln',m:-1},
  {t:'Religious symbols should be kept out of public institutions.',ax:'reln',m:1},
  {t:'Our moral values come primarily from religious tradition.',ax:'reln',m:-1},
  {t:'Religious leaders should stay out of politics.',ax:'reln',m:1},
  {t:'A nation is stronger when its people share a common religious faith.',ax:'reln',m:-1},
  {t:'Marriage, family and morality should follow religious teaching.',ax:'reln',m:-1},
  {t:'People are perfectly capable of being moral without religion.',ax:'reln',m:1},
  // tact
  {t:'Change should happen gradually through existing institutions.',ax:'tact',m:1},
  {t:'The current system is broken and must be replaced entirely.',ax:'tact',m:-1},
  {t:'Working within the system is the best way to improve society.',ax:'tact',m:1},
  {t:'Sometimes a revolution is necessary to achieve justice.',ax:'tact',m:-1},
  {t:'Radical, sweeping change usually does more harm than good.',ax:'tact',m:1},
  {t:'Protest and civil disobedience are legitimate tools for change.',ax:'tact',m:-1},
  {t:'Existing institutions can be trusted to deliver real progress.',ax:'tact',m:1},
  {t:'The established order should be overthrown, not merely reformed.',ax:'tact',m:-1},
  {t:'Steady compromise achieves more than confrontation.',ax:'tact',m:1},
  {t:'Only mass movements from below can create real change.',ax:'tact',m:-1},
  {t:'Reforming the system step by step is wiser than tearing it down.',ax:'tact',m:1},
  // mil
  {t:'Military spending should be reduced significantly.',ax:'mil',m:1},
  {t:'A strong military is essential to national greatness.',ax:'mil',m:-1},
  {t:'Diplomacy should always be tried before the use of force.',ax:'mil',m:1},
  {t:'Military intervention abroad is often justified.',ax:'mil',m:-1},
  {t:'War is almost never justified.',ax:'mil',m:1},
  {t:'Nuclear weapons should be abolished worldwide.',ax:'mil',m:1},
  {t:'Increasing defence spending should be a top national priority.',ax:'mil',m:-1},
  {t:'Our country should avoid getting involved in foreign wars.',ax:'mil',m:1},
  {t:'A powerful army is the best guarantee of peace.',ax:'mil',m:-1},
  {t:'Arms sales to other countries should be banned.',ax:'mil',m:1},
  {t:'Sometimes force is the only language aggressors understand.',ax:'mil',m:-1},
  // prop
  {t:'Major industries should be nationalised and run for public benefit.',ax:'prop',m:1},
  {t:'Private property is a sacred right that must be strongly protected.',ax:'prop',m:-1},
  {t:'Land and natural resources should be held in common.',ax:'prop',m:1},
  {t:'People have the right to accumulate unlimited private wealth.',ax:'prop',m:-1},
  {t:'Inheritance of large fortunes should be heavily taxed or abolished.',ax:'prop',m:1},
  {t:'Cooperatives and public ownership should replace big private firms.',ax:'prop',m:1},
  {t:'The means of production should remain in private hands.',ax:'prop',m:-1},
  {t:'Housing should be treated as a public good, not an investment.',ax:'prop',m:1},
  {t:'Billionaires are a sign of a healthy, successful economy.',ax:'prop',m:-1},
  {t:'Key resources like water should never be privately owned.',ax:'prop',m:1},
  {t:'Private enterprise, not the state, should own most of the economy.',ax:'prop',m:-1},
  // welf
  {t:'Healthcare should be free and provided by the state.',ax:'welf',m:1},
  {t:'People should rely on themselves, not government support.',ax:'welf',m:-1},
  {t:'A strong welfare safety net makes society stronger.',ax:'welf',m:1},
  {t:'Generous welfare makes people lazy and dependent.',ax:'welf',m:-1},
  {t:'Education should be free at all levels.',ax:'welf',m:1},
  {t:'Pensions and unemployment support should be generous.',ax:'welf',m:1},
  {t:'Government should guarantee a job to everyone who wants one.',ax:'welf',m:1},
  {t:'Welfare spending should be cut in order to lower taxes.',ax:'welf',m:-1},
  {t:'The state should provide affordable housing for all.',ax:'welf',m:1},
  {t:'Charity and family, not government, should help those in need.',ax:'welf',m:-1},
  {t:'Everyone deserves a guaranteed minimum standard of living.',ax:'welf',m:1},
  // imm
  {t:'Immigration enriches our culture and our economy.',ax:'imm',m:1},
  {t:'Immigration should be strictly limited to protect our culture.',ax:'imm',m:-1},
  {t:'We have a moral duty to welcome refugees.',ax:'imm',m:1},
  {t:'A nation should always prioritise its native-born citizens.',ax:'imm',m:-1},
  {t:'Multiculturalism strengthens society.',ax:'imm',m:1},
  {t:'Border walls and strict controls are necessary.',ax:'imm',m:-1},
  {t:'Immigrants should be required to culturally assimilate.',ax:'imm',m:-1},
  {t:'Legal immigration should be increased.',ax:'imm',m:1},
  {t:'High immigration threatens our national identity.',ax:'imm',m:-1},
  {t:'A diversity of cultures and religions is good for a country.',ax:'imm',m:1},
  {t:'Our country already accepts too many immigrants.',ax:'imm',m:-1},
  // just
  {t:'The justice system should focus on rehabilitation over punishment.',ax:'just',m:1},
  {t:'Criminals deserve harsh punishment rather than second chances.',ax:'just',m:-1},
  {t:'Prison should aim to reintegrate offenders back into society.',ax:'just',m:1},
  {t:'Longer, tougher prison sentences make society safer.',ax:'just',m:-1},
  {t:'The death penalty should be abolished everywhere.',ax:'just',m:1},
  {t:'Drug addiction should be treated as a health issue, not a crime.',ax:'just',m:1},
  {t:'We need more police and stricter law enforcement.',ax:'just',m:-1},
  {t:'Social programs prevent crime better than harsh punishment.',ax:'just',m:1},
  {t:'Being soft on crime endangers ordinary people.',ax:'just',m:-1},
  {t:'Even serious offenders can be reformed and given a second chance.',ax:'just',m:1},
  {t:'Zero-tolerance policing is the best way to cut crime.',ax:'just',m:-1}
];

/* ============ Tailored country questions (real figures, parties & events) ============ */
const COUNTRY_Q = {
  US: [
    {t:'Donald Trump has been good for the United States.',ax:'dipl',m:-1},
    {t:'The MAGA movement is a positive force in American politics.',ax:'scty',m:-1},
    {t:'Joe Biden was a good president.',ax:'econ',m:1},
    {t:'The January 6th storming of the Capitol was an attack on democracy.',ax:'dmcy',m:1},
    {t:'The 2020 election was legitimate and fairly won by Joe Biden.',ax:'dmcy',m:1},
    {t:'Overturning Roe v. Wade was the right decision.',ax:'scty',m:-1},
    {t:'Bernie Sanders-style democratic socialism is right for America.',ax:'econ',m:1},
    {t:'Trump was right to put tariffs on foreign goods.',ax:'dipl',m:-1},
    {t:'The Black Lives Matter movement has been a positive force.',ax:'scty',m:1},
    {t:'A wall along the southern border is necessary.',ax:'imm',m:-1},
    {t:'The United States should keep funding Ukraine against Russia.',ax:'mil',m:-1},
    {t:'A government-run Medicare for All system should be adopted.',ax:'welf',m:1},
    {t:'The Second Amendment should not be restricted by new gun laws.',ax:'civil',m:1},
    {t:'Ending affirmative action in college admissions was the right call.',ax:'scty',m:-1},
    {t:'Climate change demands a Green New Deal.',ax:'ecol',m:1},
    {t:'The influence of billionaires like Elon Musk on politics is a good thing.',ax:'econ',m:-1},
    {t:'Capital punishment should remain legal.',ax:'just',m:-1},
    {t:'Reforming or redirecting police funding toward social services is a good idea.',ax:'just',m:1},
    {t:'Marijuana should be legalised nationwide.',ax:'civil',m:1},
    {t:'The Electoral College should be abolished in favour of the popular vote.',ax:'dmcy',m:1},
    {t:'Christianity should have a larger role in American government.',ax:'reln',m:-1},
    {t:'The United States spends too much on its military.',ax:'mil',m:1},
    {t:'Extreme wealth should be capped; billionaires should not exist.',ax:'prop',m:1},
    {t:'Immigration makes America stronger.',ax:'imm',m:1},
    {t:'States should have far more power relative to the federal government.',ax:'state',m:1},
    {t:'Free trade deals like NAFTA have hurt American workers.',ax:'dipl',m:-1},
    {t:'LGBTQ+ rights should be protected by federal law.',ax:'scty',m:1},
    {t:'Labor unions are good for American workers.',ax:'econ',m:1},
    {t:'Withdrawing from international climate agreements was the right move.',ax:'ecol',m:-1},
    {t:'The government should guarantee paid family and medical leave.',ax:'welf',m:1},
    {t:'The Supreme Court has become too politicised.',ax:'dmcy',m:1},
    {t:'Patriotic education should be mandatory in public schools.',ax:'scty',m:-1}
  ],
  GB: [
    {t:'Brexit was the right decision for Britain.',ax:'dipl',m:-1},
    {t:'Nigel Farage and Reform UK offer what Britain needs.',ax:'imm',m:-1},
    {t:'Keir Starmer\u2019s Labour government is good for the country.',ax:'econ',m:1},
    {t:'Boris Johnson was a good Prime Minister.',ax:'dipl',m:-1},
    {t:'The monarchy should be abolished in favour of an elected head of state.',ax:'scty',m:1},
    {t:'The NHS should remain publicly funded and free at the point of use.',ax:'welf',m:1},
    {t:'Scotland should become an independent country.',ax:'state',m:1},
    {t:'The Rwanda deportation scheme was good policy.',ax:'imm',m:-1},
    {t:'The UK should rejoin the European Union.',ax:'dipl',m:1},
    {t:'Britain should keep its Trident nuclear deterrent.',ax:'mil',m:-1},
    {t:'Immigration into the UK is too high.',ax:'imm',m:-1},
    {t:'The House of Lords should be abolished or fully elected.',ax:'dmcy',m:1},
    {t:'Boris Johnson\u2019s 2019 suspension of Parliament was wrong.',ax:'dmcy',m:1},
    {t:'The monarchy is a valuable national institution worth keeping.',ax:'scty',m:-1},
    {t:'The railways and water companies should be renationalised.',ax:'prop',m:1},
    {t:'The UK should pursue net zero by 2050 as a priority.',ax:'ecol',m:1},
    {t:'Private schools should lose their charitable tax breaks.',ax:'econ',m:1},
    {t:'The right to strike should be firmly protected.',ax:'econ',m:1},
    {t:'University tuition fees should be abolished.',ax:'welf',m:1},
    {t:'Britain should be proud of the British Empire.',ax:'scty',m:-1},
    {t:'Proportional representation should replace first-past-the-post.',ax:'dmcy',m:1},
    {t:'Transgender rights and self-identification should be supported.',ax:'scty',m:1},
    {t:'The BBC licence fee should be abolished.',ax:'econ',m:-1},
    {t:'Tougher sentencing and law-and-order policies are needed.',ax:'just',m:-1},
    {t:'More power should be devolved to English regions and cities.',ax:'state',m:1},
    {t:'The Church of England should be separated from the state.',ax:'reln',m:1},
    {t:'ULEZ-style clean air zones are good for cities.',ax:'ecol',m:1},
    {t:'The UK should cut its foreign aid budget.',ax:'dipl',m:-1}
  ],
  AU: [
    {t:'The 2023 Indigenous Voice to Parliament referendum should have passed.',ax:'scty',m:1},
    {t:'Anthony Albanese\u2019s Labor government is good for Australia.',ax:'econ',m:1},
    {t:'Peter Dutton and the Coalition would offer better leadership.',ax:'econ',m:-1},
    {t:'Pauline Hanson\u2019s One Nation represents legitimate concerns.',ax:'imm',m:-1},
    {t:'Australia should become a republic.',ax:'scty',m:1},
    {t:'The AUKUS nuclear submarine deal is good for Australia.',ax:'mil',m:-1},
    {t:'Australia should phase out coal and gas exports.',ax:'ecol',m:1},
    {t:'Immigration to Australia is too high.',ax:'imm',m:-1},
    {t:'Offshore detention of asylum seekers should end.',ax:'imm',m:1},
    {t:'Medicare should be expanded and kept fully public.',ax:'welf',m:1},
    {t:'Negative gearing property tax breaks should be scrapped.',ax:'econ',m:1},
    {t:'Australia Day should be moved from January 26th.',ax:'scty',m:1},
    {t:'Australia\u2019s strict gun laws should be maintained.',ax:'civil',m:-1},
    {t:'Australia should reduce its economic reliance on China.',ax:'dipl',m:-1},
    {t:'The mining industry is vital and should be protected.',ax:'ecol',m:-1},
    {t:'University should be free or much cheaper.',ax:'welf',m:1},
    {t:'Legalising same-sex marriage was a positive change.',ax:'scty',m:1},
    {t:'Compulsory voting is a good thing for democracy.',ax:'dmcy',m:1},
    {t:'The states should have more power than the federal government in Canberra.',ax:'state',m:1},
    {t:'Renewables should be prioritised over new fossil-fuel projects.',ax:'ecol',m:1},
    {t:'The ABC public broadcaster should be well funded.',ax:'econ',m:1},
    {t:'Religion should have more influence in Australian politics.',ax:'reln',m:-1},
    {t:'Tougher sentencing and law-and-order policies are needed.',ax:'just',m:-1},
    {t:'The wealthy should pay higher taxes to fund public services.',ax:'econ',m:1}
  ],
  CA: [
    {t:'Justin Trudeau was a good Prime Minister.',ax:'scty',m:1},
    {t:'Pierre Poilievre and the Conservatives offer what Canada needs.',ax:'econ',m:-1},
    {t:'The 2022 \u2018Freedom Convoy\u2019 trucker protest was a legitimate protest.',ax:'civil',m:1},
    {t:'Invoking the Emergencies Act to end the convoy was justified.',ax:'civil',m:-1},
    {t:'The federal carbon tax is good policy.',ax:'ecol',m:1},
    {t:'Canada\u2019s universal healthcare should stay public and be strengthened.',ax:'welf',m:1},
    {t:'Immigration levels into Canada are too high.',ax:'imm',m:-1},
    {t:'Quebec should have the right to become an independent country.',ax:'state',m:1},
    {t:'Canada should keep the British monarch as its head of state.',ax:'scty',m:-1},
    {t:'Multiculturalism is one of Canada\u2019s greatest strengths.',ax:'imm',m:1},
    {t:'Canada should increase military spending to meet NATO targets.',ax:'mil',m:-1},
    {t:'Canada\u2019s gun ownership laws should be relaxed.',ax:'civil',m:1},
    {t:'Indigenous reconciliation should be a top national priority.',ax:'scty',m:1},
    {t:'The wealthy and big corporations should pay higher taxes.',ax:'econ',m:1},
    {t:'Canada should rapidly wind down the Alberta oil sands.',ax:'ecol',m:1},
    {t:'Assisted dying (MAID) laws are a positive step.',ax:'civil',m:1},
    {t:'The government should provide universal dental care and pharmacare.',ax:'welf',m:1},
    {t:'Provinces should have more autonomy from Ottawa.',ax:'state',m:1},
    {t:'Canada should welcome more refugees.',ax:'imm',m:1},
    {t:'Tougher criminal sentencing is needed in Canada.',ax:'just',m:-1},
    {t:'Protecting Canadian industries through supply management is good policy.',ax:'dipl',m:-1},
    {t:'Religion should play a bigger role in Canadian public life.',ax:'reln',m:-1},
    {t:'Proportional representation should replace first-past-the-post.',ax:'dmcy',m:1},
    {t:'Bilingualism in English and French should remain official policy.',ax:'scty',m:1}
  ],
  DE: [
    {t:'Angela Merkel\u2019s long chancellorship was good for Germany.',ax:'econ',m:1},
    {t:'The AfD (Alternative f\u00fcr Deutschland) raises legitimate concerns.',ax:'imm',m:-1},
    {t:'Merkel was right to welcome over a million refugees in 2015.',ax:'imm',m:1},
    {t:'Germany should complete its phase-out of coal power.',ax:'ecol',m:1},
    {t:'The constitutional \u2018debt brake\u2019 on spending should be relaxed.',ax:'econ',m:1},
    {t:'Germany should increase military spending and keep supporting Ukraine.',ax:'mil',m:-1},
    {t:'Immigration into Germany is too high.',ax:'imm',m:-1},
    {t:'The European Union should become more deeply integrated.',ax:'dipl',m:1},
    {t:'Germany should take a harder line against Russia.',ax:'dipl',m:-1},
    {t:'The social market economy and strong welfare state should be protected.',ax:'welf',m:1},
    {t:'Same-sex and LGBTQ rights should be fully protected.',ax:'scty',m:1},
    {t:'Germany should keep openly remembering and atoning for its history.',ax:'scty',m:1},
    {t:'The minimum wage should be raised significantly.',ax:'econ',m:1},
    {t:'Legalising cannabis was a positive step.',ax:'civil',m:1},
    {t:'Asylum rules should be tightened and immigration reduced.',ax:'imm',m:-1},
    {t:'The Energiewende shift to renewable energy should be accelerated.',ax:'ecol',m:1},
    {t:'National pride in Germany should be more openly encouraged.',ax:'dipl',m:-1},
    {t:'The wealthy should pay higher taxes.',ax:'econ',m:1},
    {t:'Religion should have more influence in German politics.',ax:'reln',m:-1},
    {t:'The federal states (L\u00e4nder) should have more power.',ax:'state',m:1},
    {t:'Germany should support shared EU debt and deeper fiscal union.',ax:'dipl',m:1},
    {t:'Tougher law and order and policing are needed.',ax:'just',m:-1}
  ],
  FR: [
    {t:'Emmanuel Macron has been good for France.',ax:'econ',m:-1},
    {t:'Marine Le Pen and the National Rally offer what France needs.',ax:'imm',m:-1},
    {t:'Jean-Luc M\u00e9lenchon\u2019s left-wing programme is right for France.',ax:'econ',m:1},
    {t:'Raising the retirement age to 64 was a mistake.',ax:'welf',m:1},
    {t:'France\u2019s strict secularism (la\u00efcit\u00e9) should be firmly upheld.',ax:'reln',m:1},
    {t:'Banning conspicuous religious symbols in public schools is justified.',ax:'reln',m:1},
    {t:'Immigration into France is too high.',ax:'imm',m:-1},
    {t:'The Yellow Vests (Gilets Jaunes) protests were justified.',ax:'econ',m:1},
    {t:'France should rapidly expand renewable energy.',ax:'ecol',m:1},
    {t:'A wealth tax on the richest should be reinstated.',ax:'prop',m:1},
    {t:'The European Union should have more power over member states.',ax:'dipl',m:1},
    {t:'France should act independently and reduce US and NATO influence.',ax:'dipl',m:-1},
    {t:'Same-sex marriage and LGBTQ rights are a positive for France.',ax:'scty',m:1},
    {t:'Strong law and order and tougher policing are needed.',ax:'just',m:-1},
    {t:'The 35-hour week and strong labour protections should be kept.',ax:'econ',m:1},
    {t:'France should take a tougher stance on immigration and integration.',ax:'imm',m:-1},
    {t:'Public healthcare and welfare should be expanded.',ax:'welf',m:1},
    {t:'French national identity and pride should be actively promoted.',ax:'dipl',m:-1},
    {t:'Power should be decentralised to France\u2019s regions.',ax:'state',m:1},
    {t:'Tackling climate change should take priority over economic growth.',ax:'ecol',m:1},
    {t:'The wealthy should pay much higher taxes.',ax:'econ',m:1},
    {t:'A strong president who can act decisively is better than messy coalitions.',ax:'dmcy',m:-1}
  ],
  IN: [
    {t:'Narendra Modi has been good for India.',ax:'dipl',m:-1},
    {t:'The BJP\u2019s Hindu-nationalist vision is good for the country.',ax:'reln',m:-1},
    {t:'The Citizenship Amendment Act (CAA) was the right policy.',ax:'imm',m:-1},
    {t:'India should remain a secular state that favours no religion.',ax:'reln',m:1},
    {t:'The Congress party\u2019s secular, welfare vision is better for India.',ax:'econ',m:1},
    {t:'Caste-based reservations (affirmative action) should continue.',ax:'scty',m:1},
    {t:'Removing Article 370\u2019s special status for Kashmir was justified.',ax:'dipl',m:-1},
    {t:'India should prioritise rapid free-market economic growth.',ax:'econ',m:-1},
    {t:'The farmers were right to protest the 2020 farm laws.',ax:'econ',m:1},
    {t:'India should build a much stronger welfare state for the poor.',ax:'welf',m:1},
    {t:'Cow-protection laws should be strictly enforced.',ax:'reln',m:-1},
    {t:'India should take a hard military line against Pakistan and China.',ax:'mil',m:-1},
    {t:'Women\u2019s rights and gender equality should be a top priority.',ax:'scty',m:1},
    {t:'Inequality should be reduced through higher taxes on the rich.',ax:'econ',m:1},
    {t:'A strong central government is better than powerful state governments.',ax:'state',m:-1},
    {t:'Freedom of the press and the right to dissent must be fully protected.',ax:'civil',m:1},
    {t:'India should transition away from coal toward renewables.',ax:'ecol',m:1},
    {t:'Western influence should give way to Indian tradition and culture.',ax:'scty',m:-1},
    {t:'LGBTQ rights should be fully recognised in India.',ax:'scty',m:1},
    {t:'A powerful decisive leader is better for India than coalition politics.',ax:'dmcy',m:-1},
    {t:'India\u2019s democratic institutions should be strengthened against concentration of power.',ax:'dmcy',m:1},
    {t:'State-owned industries should be privatised.',ax:'prop',m:-1}
  ],
  NZ: [
    {t:'Jacinda Ardern was a good Prime Minister.',ax:'scty',m:1},
    {t:'Christopher Luxon and the National Party offer better leadership.',ax:'econ',m:-1},
    {t:'The Treaty of Waitangi and M\u0101ori rights should be strengthened.',ax:'scty',m:1},
    {t:'Attempts to weaken the Treaty principles are a bad idea.',ax:'scty',m:1},
    {t:'The strict gun laws passed after the Christchurch attack were right.',ax:'civil',m:-1},
    {t:'New Zealand should remain proudly nuclear-free.',ax:'mil',m:1},
    {t:'New Zealand should become a republic.',ax:'scty',m:1},
    {t:'Immigration into New Zealand is too high.',ax:'imm',m:-1},
    {t:'Public healthcare should be well funded and free.',ax:'welf',m:1},
    {t:'New Zealand should take strong action on climate change.',ax:'ecol',m:1},
    {t:'The wealthy should pay higher taxes, including a capital gains tax.',ax:'econ',m:1},
    {t:'Te reo M\u0101ori and biculturalism should be actively promoted.',ax:'scty',m:1},
    {t:'New Zealand should align more closely with the US on security.',ax:'dipl',m:-1},
    {t:'University and education should be much more affordable.',ax:'welf',m:1},
    {t:'Cannabis should be legalised.',ax:'civil',m:1},
    {t:'Same-sex and LGBTQ rights are a positive for society.',ax:'scty',m:1},
    {t:'Tougher law-and-order policies are needed.',ax:'just',m:-1},
    {t:'Farming should be protected from strict environmental rules.',ax:'ecol',m:-1},
    {t:'Local councils should be given more power.',ax:'state',m:1},
    {t:'Religion should have more influence in politics.',ax:'reln',m:-1}
  ],
  IE: [
    {t:'Sinn F\u00e9in offers the leadership Ireland needs.',ax:'econ',m:1},
    {t:'Ireland should be reunified with Northern Ireland.',ax:'state',m:1},
    {t:'Legalising abortion by repealing the Eighth Amendment was right.',ax:'scty',m:1},
    {t:'Same-sex marriage was a positive change for Ireland.',ax:'scty',m:1},
    {t:'The Catholic Church should have less influence over Irish society.',ax:'reln',m:1},
    {t:'Immigration into Ireland is too high.',ax:'imm',m:-1},
    {t:'Ireland\u2019s low corporate tax rate should be protected.',ax:'econ',m:-1},
    {t:'The housing crisis requires a big state-led public housing programme.',ax:'welf',m:1},
    {t:'Ireland should remain militarily neutral.',ax:'mil',m:1},
    {t:'The European Union has been good for Ireland.',ax:'dipl',m:1},
    {t:'The wealthy and big corporations should pay higher taxes.',ax:'econ',m:1},
    {t:'The Irish language and culture should be actively promoted.',ax:'dipl',m:-1},
    {t:'Public healthcare (Sl\u00e1intecare) should be fully funded and universal.',ax:'welf',m:1},
    {t:'Ireland should take strong action on climate change.',ax:'ecol',m:1},
    {t:'Tougher law and order is needed.',ax:'just',m:-1},
    {t:'LGBTQ rights should be fully protected.',ax:'scty',m:1},
    {t:'The asylum system (direct provision) should be reformed to be more humane.',ax:'imm',m:1},
    {t:'Ireland should welcome more refugees.',ax:'imm',m:1},
    {t:'Local and regional government should have more power.',ax:'state',m:1},
    {t:'Religion should play a bigger role in public life.',ax:'reln',m:-1}
  ]
};

/* ============ Ideologies ============ */
/* coords 0-100 on 7 axes: [eq, lb, dm, pr, gl, sc, ec]
   eq=Equality lb=Liberty dm=Democracy pr=Progress gl=Globalism sc=Secular ec=Ecology */
const IDEOLOGIES = [
  {n:'Anarcho-Communism',c:[95,92,85,82,82,82,72],d:'A stateless, classless society built on voluntary communes and common ownership, combining radical equality with maximum personal freedom.'},
  {n:'Anarcho-Syndicalism',c:[90,86,85,76,72,76,70],d:'Workers run society through revolutionary trade unions, abolishing the state in favour of federated worker councils.'},
  {n:'Libertarian Socialism',c:[86,88,88,80,74,74,76],d:'Socialism without a coercive state, emphasising self-management, direct democracy and decentralised common ownership.'},
  {n:'Council Communism',c:[94,74,80,74,74,80,60],d:'Rule by democratic workers\u2019 councils rather than a party or bureaucracy, rejecting both capitalism and one-party rule.'},
  {n:'Left-Communism',c:[96,58,55,72,86,82,56],d:'A revolutionary Marxist current critical of both parliamentary reform and authoritarian party-states.'},
  {n:'Trotskyism',c:[95,44,45,76,90,86,55],d:'Revolutionary Marxism advocating international permanent revolution and opposition to bureaucratic one-party rule.'},
  {n:'Marxism\u2013Leninism',c:[95,15,20,68,66,86,48],d:'A vanguard party leads a centralised state to abolish private ownership of the means of production.'},
  {n:'Maoism',c:[95,20,18,64,52,80,46],d:'A peasant-based revolutionary communism built on continuous class struggle and mass mobilisation.'},
  {n:'Stalinism',c:[90,8,5,52,38,80,36],d:'A highly centralised, authoritarian Marxism\u2013Leninism built on a powerful one-party state and command economy.'},
  {n:'Democratic Socialism',c:[82,66,82,76,66,66,70],d:'Aims for a socialist economy achieved democratically, with extensive public ownership and strong civil liberties.'},
  {n:'Social Democracy',c:[70,64,85,70,66,60,64],d:'A regulated market economy with a generous welfare state, strong unions and redistribution within democracy.'},
  {n:'Eco-Socialism / Green Left',c:[82,70,80,82,76,68,97],d:'Merges socialism with environmentalism, arguing ecological survival requires ending profit-driven growth.'},
  {n:'Progressivism',c:[63,70,82,86,70,70,70],d:'Focuses on social reform, expanding rights and using government to correct injustice and inequality.'},
  {n:'Social Liberalism',c:[58,72,85,73,68,64,60],d:'Combines a market economy with civil liberties, a welfare safety net and progressive social values.'},
  {n:'Left-Populism',c:[76,52,70,62,40,56,56],d:'Champions ordinary people against economic elites, favouring redistribution and often economic nationalism.'},
  {n:'Mutualism',c:[70,80,82,66,60,64,66],d:'A market socialism based on cooperatives, mutual credit and workers owning what they produce, with a minimal state.'},
  {n:'Georgism',c:[60,66,78,62,60,60,72],d:'Argues land and natural resources belong to all, funding society through a land-value tax while keeping free markets.'},
  {n:'Distributism',c:[56,52,60,40,42,32,55],d:'Seeks to spread property ownership as widely as possible, rooted in family, community and Christian social teaching.'},
  {n:'Classical Liberalism',c:[40,80,78,60,60,60,42],d:'Prioritises individual liberty, constitutional government, free markets and limited state power.'},
  {n:'Neoliberalism',c:[26,60,68,56,72,60,36],d:'Favours free markets, deregulation, privatisation and global trade, with a limited economic role for the state.'},
  {n:'Libertarianism',c:[20,92,72,56,55,64,35],d:'Maximum individual freedom in personal and economic life, with a very small state and strong property rights.'},
  {n:'Anarcho-Capitalism',c:[10,95,55,52,52,58,26],d:'Would abolish the state entirely, replacing all public functions with private property and voluntary exchange.'},
  {n:'Minarchism',c:[22,86,70,54,52,58,32],d:'A night-watchman state limited to police, courts and defence, leaving everything else to free markets.'},
  {n:'Centrism',c:[50,52,75,52,52,52,50],d:'Rejects strong ideology, favouring pragmatic, moderate policy that balances left and right.'},
  {n:'Third Way',c:[54,60,78,62,68,58,56],d:'A centre-left blend of market economics with social investment and modernised public services.'},
  {n:'Christian Democracy',c:[50,46,70,40,55,26,52],d:'A centre-right tradition blending market economics with a welfare state and conservative Christian social values.'},
  {n:'One-Nation Conservatism',c:[48,46,68,36,50,42,46],d:'A paternalistic conservatism that accepts the welfare state to preserve social unity and stability.'},
  {n:'Conservatism',c:[35,42,65,26,42,38,36],d:'Values tradition, order, national institutions and gradual change, with a preference for free enterprise.'},
  {n:'Liberal Conservatism',c:[38,52,70,42,55,50,40],d:'Combines free-market economics and individual liberty with respect for tradition and social order.'},
  {n:'Neoconservatism',c:[30,36,60,40,48,52,32],d:'Right-leaning economics paired with an assertive, interventionist foreign policy promoting national values abroad.'},
  {n:'Right-Populism',c:[38,30,45,24,16,46,26],d:'Champions the people against elites and outsiders, combining nationalism, social conservatism and border control.'},
  {n:'National Conservatism',c:[42,28,40,18,15,28,32],d:'Emphasises nation, family, tradition and strong borders, with deep scepticism of globalisation.'},
  {n:'Traditionalist Conservatism',c:[38,28,35,12,32,14,32],d:'Prioritises religion, hierarchy and inherited custom, resisting most social and cultural change.'},
  {n:'Nationalism',c:[42,30,40,30,8,46,36],d:'Places the interests, identity and sovereignty of the nation above all other political concerns.'},
  {n:'Constitutional Monarchism',c:[50,55,65,45,55,45,50],d:'Retains a hereditary monarch as head of state within a democratic constitution that limits royal power.'},
  {n:'Absolute Monarchism',c:[46,12,8,12,35,22,42],d:'Rule by a hereditary monarch holding supreme, largely unchecked authority over the state.'},
  {n:'Reactionary Traditionalism',c:[40,18,20,6,28,12,34],d:'Seeks to reverse modern change and restore an idealised social, religious and political order of the past.'},
  {n:'Theocracy',c:[46,10,10,8,30,3,36],d:'Government founded on religious law and clerical authority, where faith directly governs public life.'},
  {n:'Religious Fundamentalism',c:[48,10,10,5,26,2,38],d:'Insists that strict religious doctrine should shape law, morality and the structure of the state.'},
  {n:'Christian Nationalism',c:[36,20,30,10,20,8,30],d:'Fuses national identity with a dominant Christian religious character enforced through the state.'},
  {n:'Falangism',c:[42,10,10,18,15,12,26],s:1,d:'An authoritarian nationalist movement blending corporatism, traditional religion and a single-party state.'},
  {n:'Fascism',c:[32,7,5,24,10,48,26],s:1,d:'A dictatorial, ultranationalist ideology built on a one-party state, suppression of dissent and militarism. Listed for historical understanding, not endorsement.'},
  {n:'National Socialism',c:[35,5,3,14,4,42,28],s:1,d:'The racist, totalitarian ideology of Nazi Germany, combining ultranationalism, dictatorship and genocidal racial doctrine. Listed for historical understanding, not endorsement.'},
  {n:'Green Environmentalism',c:[60,64,82,72,68,62,96],d:'Places ecological sustainability at the centre of politics, favouring strong environmental protection and grassroots democracy.'},
  {n:'Technocracy',c:[52,42,45,56,62,66,56],d:'Government by scientific and technical experts who make decisions on evidence rather than popular opinion.'},
  {n:'Feminism',c:[68,70,80,90,68,66,64],d:'Seeks full political, economic and social equality between the sexes and the dismantling of patriarchal structures.'},
  {n:'Agrarianism',c:[55,50,60,30,30,35,72],d:'Champions rural life, farming communities and land stewardship as the moral foundation of society.'},
  {n:'Cosmopolitan Globalism',c:[56,62,75,66,96,64,60],d:'Views humanity as a single global community, favouring open borders, global governance and world citizenship.'}
];

/* ============ Parties by country ============ */
/* coords 0-100 on [eq, lb, pr] = [Equality, Liberty, Progress] */
const PARTIES = {
  US: [
    {n:'Democratic Party',c:[62,60,70]},
    {n:'Republican Party',c:[30,36,26]},
    {n:'Libertarian Party',c:[24,90,56]},
    {n:'Green Party',c:[80,70,86]},
    {n:'Progressive Left',c:[84,68,84]},
    {n:'Constitution Party',c:[30,20,10]}
  ],
  GB: [
    {n:'Labour Party',c:[65,58,68]},
    {n:'Conservative Party',c:[35,40,30]},
    {n:'Liberal Democrats',c:[54,72,72]},
    {n:'Green Party',c:[78,72,86]},
    {n:'Reform UK',c:[34,32,16]},
    {n:'Scottish National Party',c:[62,60,68]},
    {n:'Plaid Cymru',c:[68,62,72]}
  ],
  AU: [
    {n:'Labor Party',c:[62,56,65]},
    {n:'Liberal Party',c:[33,42,32]},
    {n:'The Nationals',c:[36,35,22]},
    {n:'The Greens',c:[80,70,86]},
    {n:'One Nation',c:[36,26,12]}
  ],
  CA: [
    {n:'Liberal Party',c:[58,60,68]},
    {n:'Conservative Party',c:[33,42,30]},
    {n:'New Democratic Party (NDP)',c:[76,62,78]},
    {n:'Bloc Qu\u00e9b\u00e9cois',c:[62,58,70]},
    {n:'Green Party',c:[74,68,84]},
    {n:'People\u2019s Party (PPC)',c:[30,30,16]}
  ],
  DE: [
    {n:'SPD (Social Democrats)',c:[66,60,68]},
    {n:'CDU/CSU (Christian Democrats)',c:[40,46,38]},
    {n:'Alliance 90/The Greens',c:[72,68,84]},
    {n:'FDP (Free Democrats)',c:[30,66,60]},
    {n:'AfD',c:[34,26,14]},
    {n:'Die Linke (The Left)',c:[88,58,78]}
  ],
  FR: [
    {n:'Renaissance (Macron)',c:[42,58,60]},
    {n:'National Rally',c:[36,26,18]},
    {n:'La France Insoumise',c:[82,54,72]},
    {n:'Les R\u00e9publicains',c:[34,40,30]},
    {n:'Socialist Party',c:[66,60,70]},
    {n:'The Greens (EELV)',c:[72,66,84]}
  ],
  IN: [
    {n:'Bharatiya Janata Party (BJP)',c:[40,32,22]},
    {n:'Indian National Congress',c:[58,58,62]},
    {n:'Aam Aadmi Party (AAP)',c:[60,56,60]},
    {n:'CPI(M) / Left Front',c:[88,50,70]},
    {n:'Regional / Others',c:[52,50,50]}
  ],
  NZ: [
    {n:'Labour Party',c:[62,58,68]},
    {n:'National Party',c:[34,44,34]},
    {n:'Green Party',c:[80,70,86]},
    {n:'ACT New Zealand',c:[24,70,52]},
    {n:'New Zealand First',c:[40,34,26]},
    {n:'Te P\u0101ti M\u0101ori',c:[72,62,80]}
  ],
  IE: [
    {n:'Fianna F\u00e1il',c:[48,50,50]},
    {n:'Fine Gael',c:[38,52,48]},
    {n:'Sinn F\u00e9in',c:[70,56,66]},
    {n:'Green Party',c:[72,66,84]},
    {n:'Labour Party',c:[64,60,70]},
    {n:'Social Democrats',c:[70,64,76]},
    {n:'People Before Profit',c:[90,60,82]}
  ],
  DEFAULT: [
    {n:'Communist / Far-Left',c:[92,40,72]},
    {n:'Social-Democratic / Labour',c:[68,60,68]},
    {n:'Green / Ecologist',c:[76,68,84]},
    {n:'Liberal / Centrist',c:[50,70,64]},
    {n:'Conservative / Christian-Democratic',c:[40,42,28]},
    {n:'Libertarian / Classical-Liberal',c:[22,88,55]},
    {n:'Nationalist / Far-Right',c:[38,25,14]}
  ]
};

/* ============ Countries ============ */
/* t:1 => has a tailored question set. Flags are generated at runtime from the code. */
function flagOf(cc){
  const base='A'.charCodeAt(0);
  return cc.toUpperCase().split('').map(function(ch){return String.fromCodePoint(0x1F1E6 + ch.charCodeAt(0) - base);}).join('');
}
const COUNTRIES = [
  {c:'US',n:'United States',t:1},
  {c:'GB',n:'United Kingdom',t:1},
  {c:'CA',n:'Canada',t:1},
  {c:'AU',n:'Australia',t:1},
  {c:'NZ',n:'New Zealand',t:1},
  {c:'IE',n:'Ireland',t:1},
  {c:'DE',n:'Germany',t:1},
  {c:'FR',n:'France',t:1},
  {c:'IN',n:'India',t:1},
  {c:'IT',n:'Italy'},
  {c:'ES',n:'Spain'},
  {c:'PT',n:'Portugal'},
  {c:'NL',n:'Netherlands'},
  {c:'BE',n:'Belgium'},
  {c:'SE',n:'Sweden'},
  {c:'NO',n:'Norway'},
  {c:'DK',n:'Denmark'},
  {c:'FI',n:'Finland'},
  {c:'PL',n:'Poland'},
  {c:'AT',n:'Austria'},
  {c:'CH',n:'Switzerland'},
  {c:'GR',n:'Greece'},
  {c:'CZ',n:'Czechia'},
  {c:'HU',n:'Hungary'},
  {c:'RO',n:'Romania'},
  {c:'UA',n:'Ukraine'},
  {c:'RU',n:'Russia'},
  {c:'TR',n:'Turkey'},
  {c:'JP',n:'Japan'},
  {c:'KR',n:'South Korea'},
  {c:'CN',n:'China'},
  {c:'BR',n:'Brazil'},
  {c:'MX',n:'Mexico'},
  {c:'AR',n:'Argentina'},
  {c:'CL',n:'Chile'},
  {c:'CO',n:'Colombia'},
  {c:'ZA',n:'South Africa'},
  {c:'NG',n:'Nigeria'},
  {c:'EG',n:'Egypt'},
  {c:'SA',n:'Saudi Arabia'},
  {c:'AE',n:'United Arab Emirates'},
  {c:'IL',n:'Israel'},
  {c:'PK',n:'Pakistan'},
  {c:'BD',n:'Bangladesh'},
  {c:'ID',n:'Indonesia'},
  {c:'PH',n:'Philippines'},
  {c:'TH',n:'Thailand'},
  {c:'VN',n:'Vietnam'},
  {c:'SG',n:'Singapore'},
  {c:'MY',n:'Malaysia'}
];

if (typeof module !== 'undefined') { module.exports = { AXES, GENERAL, COUNTRY_Q, IDEOLOGIES, PARTIES, COUNTRIES, flagOf }; }
